export const STORAGE_KEYS = {
  CSS_STYLE_KEY: 'CSS_STYLE_KEY',
  IDENTIFY_COMPONENT: 'IDENTIFY_COMPONENT',
  UNIT_TYPE_KEY: 'UNIT_TYPE_KEY',
  USER_COMPONENT_SETTINGS_KEY: 'USER_COMPONENT_SETTINGS_KEY'
} as const
